import {
  Activity,
  AlertTriangle,
  Archive,
  AtSign,
  Award,
  Bell,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Boxes,
  Bug,
  Building,
  Calendar,
  Chrome,
  Cloud,
  Code,
  Coffee,
  Compass,
  Container,
  Cpu,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  Eye,
  FileCode,
  FileText,
  Flag,
  Folder,
  Gauge,
  Gift,
  GitBranch,
  GitFork,
  GitPullRequest,
  Github,
  Gitlab,
  Globe,
  GraduationCap,
  Hammer,
  HeartHandshake,
  HelpCircle,
  Home,
  Image,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Lightbulb,
  Link,
  Linkedin,
  ListChecks,
  Lock,
  Mail,
  Map,
  MessageCircle,
  Monitor,
  Newspaper,
  Package,
  Play,
  Puzzle,
  Radio,
  Rocket,
  Rss,
  Scale,
  Scroll,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Slack,
  Sparkles,
  Star,
  Tag,
  Terminal,
  Ticket,
  Trello,
  Twitch,
  Twitter,
  Upload,
  Users,
  Video,
  Wrench,
  Youtube,
  Zap,
  type LucideIcon,
} from 'lucide-react'

// Curated lucide subset offered by the footer-link icon picker. Keys are lucide's own kebab-case
// names, so adding an icon is one import plus one entry; unknown names fall back to `Link`.
export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'at-sign': AtSign,
  award: Award,
  bell: Bell,
  book: Book,
  'book-open': BookOpen,
  bookmark: Bookmark,
  box: Box,
  boxes: Boxes,
  bug: Bug,
  building: Building,
  calendar: Calendar,
  chrome: Chrome,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  container: Container,
  cpu: Cpu,
  'credit-card': CreditCard,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'file-code': FileCode,
  'file-text': FileText,
  flag: Flag,
  folder: Folder,
  gauge: Gauge,
  gift: Gift,
  'git-branch': GitBranch,
  'git-fork': GitFork,
  'git-pull-request': GitPullRequest,
  github: Github,
  gitlab: Gitlab,
  globe: Globe,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  'heart-handshake': HeartHandshake,
  'help-circle': HelpCircle,
  home: Home,
  image: Image,
  info: Info,
  key: Key,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'life-buoy': LifeBuoy,
  lightbulb: Lightbulb,
  link: Link,
  linkedin: Linkedin,
  'list-checks': ListChecks,
  lock: Lock,
  mail: Mail,
  map: Map,
  'message-circle': MessageCircle,
  monitor: Monitor,
  newspaper: Newspaper,
  package: Package,
  play: Play,
  puzzle: Puzzle,
  radio: Radio,
  rocket: Rocket,
  rss: Rss,
  scale: Scale,
  scroll: Scroll,
  server: Server,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  slack: Slack,
  sparkles: Sparkles,
  star: Star,
  tag: Tag,
  terminal: Terminal,
  ticket: Ticket,
  trello: Trello,
  twitch: Twitch,
  twitter: Twitter,
  upload: Upload,
  users: Users,
  video: Video,
  wrench: Wrench,
  youtube: Youtube,
  zap: Zap,
}

export const ICON_NAMES = Object.keys(ICONS)

export function icon(name: string): LucideIcon {
  return ICONS[name] ?? Link
}
